RedisExchangeAPI.Web/Controllers/ListTypesController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisExchangeAPI.Web.Controllers
{
    public class ListTypesController : Controller
    {
        private readonly RedisService _redisService;

        private readonly IDatabase db;

        private string listKey = "names";
        public ListTypesController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDb(2);
        }
        public IActionResult Index()
        {
            List<string> namesList = new List<string>();
            if (db.KeyExists(listKey))
            {
                db.ListRange(listKey).ToList().ForEach(x =>
                {
                    namesList.Add(x.ToString());
                });
            }

            return View(namesList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            db.ListLeftPush(listKey, name);

            return RedirectToAction("Index");
        }
   
        public IActionResult DeleteItem(string name)
        {
            db.ListRemoveAsync(listKey, name).Wait();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteFirstItem()
        {
            db.ListLeftPopAsync(listKey).Wait();
            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPI.Web/Views/ListTypes/Index.cshtml
@model IList<string>;
@{
    ViewData["Title"] = "Index";
}

<a asp-action="DeleteFirstItem">Baştan sil </a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>

</form>

@foreach (var item in Model)
{
    <h2> @item <a asp-controller="ListTypes" asp-action="DeleteItem" asp-route-name="@item">Sil</a></h2> 
     
}